# Generated by Django 5.2.2 on 2025-06-25 09:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("fixed_solutions", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("title", 1),
                                ("button_text", 1),
                                ("button_link", 2),
                            ]
                        ],
                        {},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: ("wagtail.blocks.StructBlock", [[("solutions", 4)]], {}),
                },
            ),
        ),
    ]
