# Generated by Django 5.2.2 on 2025-06-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="section_heading",
            field=models.CharField(
                default="Explore All Possibilities",
                help_text="Main heading above the solutions section",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="section_subheading",
            field=models.TextField(blank=True, help_text="Optional subheading text"),
        ),
    ]
