# Generated by Django 5.2.2 on 2025-06-25 11:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_homepage_section_heading_homepage_section_subheading"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="section_heading",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="section_subheading",
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("logo_carousel", 6)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main title", "required": True},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: (
                        "wagtail.blocks.ListBlock",
                        (1,),
                        {"help_text": "Words to rotate"},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle below the heading", "required": True},
                    ),
                    4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    5: (
                        "wagtail.blocks.ListBlock",
                        (4,),
                        {"help_text": "Upload logos"},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("rotating_words", 2),
                                ("subtitle", 3),
                                ("logos", 5),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
