# Generated by Django 5.2.2 on 2025-06-25 11:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="footer",
            field=wagtail.fields.StreamField(
                [("footer", 8)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    5: ("wagtail.blocks.CharBlock", (), {}),
                    6: ("wagtail.blocks.URLBlock", (), {}),
                    7: ("wagtail.blocks.StructBlock", [[("label", 5), ("url", 6)]], {}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("logo", 0),
                                ("description", 1),
                                ("view_more_link", 2),
                                ("address", 3),
                                ("phone", 3),
                                ("email", 4),
                                ("link_1", 7),
                                ("link_2", 7),
                                ("link_3", 7),
                                ("copyright", 5),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
