# Generated by Django 5.2.2 on 2025-06-25 12:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_homepage_footer"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_slides",
            field=wagtail.fields.StreamField(
                [("hero_slide", 8)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Small text above main heading",
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main headline", "required": True},
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description paragraph", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "GET STARTED", "required": True},
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Anchor or full URL", "required": True},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Animated word (optional)", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 1000, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 0),
                                ("heading_top", 1),
                                ("heading_main", 2),
                                ("subheading", 3),
                                ("button_text", 4),
                                ("button_link", 5),
                                ("animated_word", 6),
                                ("animation_delay", 7),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
