# Generated by Django 5.2.2 on 2025-06-25 12:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_homepage_hero_slides"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_slides",
            field=wagtail.fields.StreamField(
                [("hero_slide", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: ("wagtail.blocks.TextBlock", (), {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "GET STARTED", "required": False},
                    ),
                    5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 0),
                                ("subtitle", 1),
                                ("headline", 1),
                                ("highlight_text", 2),
                                ("description", 3),
                                ("button_text", 4),
                                ("button_link", 5),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
