# Generated by Django 5.2.2 on 2025-06-25 12:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_homepage_hero_slides"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero_carousel", 7),
                    ("fixed_solutions", 13),
                    ("logo_carousel", 19),
                    ("style_switcher", 25),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: ("wagtail.blocks.TextBlock", (), {}),
                    4: ("wagtail.blocks.CharBlock", (), {"default": "GET STARTED"}),
                    5: ("wagtail.blocks.URLBlock", (), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 0),
                                ("subtitle", 1),
                                ("headline", 1),
                                ("highlight_text", 2),
                                ("description", 3),
                                ("button_text", 4),
                                ("button_link", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.StreamBlock", [[("hero_slide", 6)]], {}),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    10: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 8),
                                ("title", 9),
                                ("button_text", 9),
                                ("button_link", 10),
                            ]
                        ],
                        {},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: ("wagtail.blocks.StructBlock", [[("solutions", 12)]], {}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main title", "required": True},
                    ),
                    15: (
                        "wagtail.blocks.ListBlock",
                        (1,),
                        {"help_text": "Words to rotate"},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle below the heading", "required": True},
                    ),
                    17: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (17,),
                        {"help_text": "Upload logos"},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 14),
                                ("rotating_words", 15),
                                ("subtitle", 16),
                                ("logos", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading", "required": True},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Highlighted word in heading", "required": True},
                    ),
                    22: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Main paragraph text", "required": True},
                    ),
                    23: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional extra paragraph", "required": False},
                    ),
                    24: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Associated image", "required": True},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 20),
                                ("highlight", 21),
                                ("description", 22),
                                ("extra_text", 23),
                                ("image", 24),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_slides",
            field=wagtail.fields.StreamField(
                [("hero_slide", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: ("wagtail.blocks.TextBlock", (), {}),
                    4: ("wagtail.blocks.CharBlock", (), {"default": "GET STARTED"}),
                    5: ("wagtail.blocks.URLBlock", (), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 0),
                                ("subtitle", 1),
                                ("headline", 1),
                                ("highlight_text", 2),
                                ("description", 3),
                                ("button_text", 4),
                                ("button_link", 5),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
