# Generated by Django 5.2.2 on 2025-06-25 12:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_remove_homepage_hero_slides_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("fixed_solutions", 5),
                    ("logo_carousel", 12),
                    ("style_switcher", 18),
                    ("hero_carousel", 21),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("title", 1),
                                ("button_text", 1),
                                ("button_link", 2),
                            ]
                        ],
                        {},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: ("wagtail.blocks.StructBlock", [[("solutions", 4)]], {}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main title", "required": True},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: (
                        "wagtail.blocks.ListBlock",
                        (7,),
                        {"help_text": "Words to rotate"},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle below the heading", "required": True},
                    ),
                    10: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {"help_text": "Upload logos"},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 6),
                                ("rotating_words", 8),
                                ("subtitle", 9),
                                ("logos", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading", "required": True},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Highlighted word in heading", "required": True},
                    ),
                    15: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Main paragraph text", "required": True},
                    ),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional extra paragraph", "required": False},
                    ),
                    17: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Associated image", "required": True},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("highlight", 14),
                                ("description", 15),
                                ("extra_text", 16),
                                ("image", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Background image for each slide"},
                    ),
                    20: (
                        "wagtail.blocks.ListBlock",
                        (19,),
                        {
                            "help_text": "Upload one or more images for the carousel",
                            "label": "Hero Carousel Slides",
                        },
                    ),
                    21: ("wagtail.blocks.StructBlock", [[("slides", 20)]], {}),
                },
            ),
        ),
    ]
