# Generated by Django 5.2.2 on 2025-06-25 13:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero_carousel", 2),
                    ("fixed_solutions", 10),
                    ("logo_carousel", 17),
                    ("style_switcher", 23),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Select the image for this carousel slide.",
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("image", 0)]], {}),
                    2: ("wagtail.blocks.ListBlock", (1,), {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main heading above the solutions section",
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional subheading text", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for the solution item", "required": True},
                    ),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Background image", "required": True},
                    ),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional link for the solution",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("image", 6), ("link", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {"help_text": "Add 5 items: 2 top, 3 bottom."},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 3), ("subheading", 4), ("solutions", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main title", "required": True},
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {}),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {"help_text": "Words to rotate"},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle below the heading", "required": True},
                    ),
                    15: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    16: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {"help_text": "Upload logos"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 11),
                                ("rotating_words", 13),
                                ("subtitle", 14),
                                ("logos", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading", "required": True},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Highlighted word in heading", "required": True},
                    ),
                    20: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Main paragraph text", "required": True},
                    ),
                    21: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional extra paragraph", "required": False},
                    ),
                    22: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Associated image", "required": True},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 18),
                                ("highlight", 19),
                                ("description", 20),
                                ("extra_text", 21),
                                ("image", 22),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
