# Generated by Django 5.2.2 on 2025-06-25 13:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero_carousel", 1),
                    ("fixed_solutions", 9),
                    ("logo_carousel", 16),
                    ("style_switcher", 22),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Select the image for this carousel slide.",
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("image", 0)]], {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main heading above the solutions section",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional subheading text", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for the solution item", "required": True},
                    ),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Background image", "required": True},
                    ),
                    6: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional link for the solution",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("image", 5), ("link", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.ListBlock",
                        (7,),
                        {"help_text": "Add 5 items: 2 top, 3 bottom."},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 2), ("subheading", 3), ("solutions", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main title", "required": True},
                    ),
                    11: ("wagtail.blocks.CharBlock", (), {}),
                    12: (
                        "wagtail.blocks.ListBlock",
                        (11,),
                        {"help_text": "Words to rotate"},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle below the heading", "required": True},
                    ),
                    14: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    15: (
                        "wagtail.blocks.ListBlock",
                        (14,),
                        {"help_text": "Upload logos"},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 10),
                                ("rotating_words", 12),
                                ("subtitle", 13),
                                ("logos", 15),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading", "required": True},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Highlighted word in heading", "required": True},
                    ),
                    19: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Main paragraph text", "required": True},
                    ),
                    20: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional extra paragraph", "required": False},
                    ),
                    21: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Associated image", "required": True},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 17),
                                ("highlight", 18),
                                ("description", 19),
                                ("extra_text", 20),
                                ("image", 21),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
