# Generated by Django 5.2.2 on 2025-06-26 07:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_alter_homepage_body"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero_section", 3),
                            ("tab_section", 9),
                            ("cta_section", 12),
                            ("footer", 13),
                        ],
                        block_lookup={
                            0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("background_image", 0),
                                        ("heading", 1),
                                        ("subheading", 2),
                                    ]
                                ],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Font Awesome class"},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {}),
                            6: ("wagtail.blocks.TextBlock", (), {}),
                            7: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 4),
                                        ("label", 5),
                                        ("heading", 5),
                                        ("description", 6),
                                        ("image", 7),
                                    ]
                                ],
                                {},
                            ),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: ("wagtail.blocks.ListBlock", (5,), {}),
                            11: ("wagtail.blocks.URLBlock", (), {}),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading", 5),
                                        ("features", 10),
                                        ("button_text", 5),
                                        ("button_link", 11),
                                    ]
                                ],
                                {},
                            ),
                            13: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "You can use simple HTML if needed"},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
