# Generated by Django 5.2.2 on 2025-06-26 07:28

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_marketingpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalFooter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", wagtail.fields.RichTextField()),
            ],
        ),
    ]
