# Generated by Django 5.2.2 on 2025-06-26 07:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_globalfooter"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingpage",
            name="footer",
            field=wagtail.fields.StreamField(
                [("footer", 8)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    5: ("wagtail.blocks.CharBlock", (), {}),
                    6: ("wagtail.blocks.URLBlock", (), {}),
                    7: ("wagtail.blocks.StructBlock", [[("label", 5), ("url", 6)]], {}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("logo", 0),
                                ("description", 1),
                                ("view_more_link", 2),
                                ("address", 3),
                                ("phone", 3),
                                ("email", 4),
                                ("link_1", 7),
                                ("link_2", 7),
                                ("link_3", 7),
                                ("copyright", 5),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="marketingpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero_section", 3), ("tab_section", 9), ("cta_section", 12)],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("background_image", 0), ("heading", 1), ("subheading", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Font Awesome class"},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {}),
                    6: ("wagtail.blocks.TextBlock", (), {}),
                    7: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 4),
                                ("label", 5),
                                ("heading", 5),
                                ("description", 6),
                                ("image", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {}),
                    10: ("wagtail.blocks.ListBlock", (5,), {}),
                    11: ("wagtail.blocks.URLBlock", (), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 5),
                                ("features", 10),
                                ("button_text", 5),
                                ("button_link", 11),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
