# Generated by Django 5.2.2 on 2025-06-26 08:18

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_alter_marketingpage_body"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("page_header", 2),
                            ("who_we_are", 6),
                            ("toggle_section", 8),
                            ("team_section", 12),
                            ("logos_carousel", 5),
                        ],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("breadcrumb", 1)]],
                                {},
                            ),
                            3: ("wagtail.blocks.RichTextBlock", (), {}),
                            4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            5: ("wagtail.blocks.ListBlock", (4,), {}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("text", 3), ("carousel_images", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("content", 3)]],
                                {},
                            ),
                            8: ("wagtail.blocks.ListBlock", (7,), {}),
                            9: ("wagtail.blocks.TextBlock", (), {}),
                            10: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 0),
                                        ("role", 0),
                                        ("image", 4),
                                        ("description", 9),
                                        ("facebook", 10),
                                        ("twitter", 10),
                                        ("linkedin", 10),
                                    ]
                                ],
                                {},
                            ),
                            12: ("wagtail.blocks.ListBlock", (11,), {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
