# Generated by Django 5.2.2 on 2025-06-26 08:49

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_aboutuspage"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Main Header", max_length=255)),
                (
                    "header",
                    wagtail.fields.StreamField(
                        [("header", 6)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Text or image placeholder"},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {}),
                            2: ("wagtail.blocks.URLBlock", (), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 1), ("url", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.ListBlock", (3,), {}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 1), ("items", 4)]],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("logo", 0),
                                        ("nav_items", 4),
                                        ("solutions_dropdown", 5),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
        ),
    ]
