# Generated by Django 5.2.2 on 2025-06-26 09:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_globalheader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalheader",
            name="header",
            field=wagtail.fields.StreamField(
                [("header", 6)],
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Upload logo image"},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.URLBlock", (), {}),
                    3: ("wagtail.blocks.StructBlock", [[("label", 1), ("url", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("items", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("logo", 0), ("nav_items", 4), ("solutions_dropdown", 5)]],
                        {},
                    ),
                },
            ),
        ),
    ]
