# Generated by Django 5.2.2 on 2025-06-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_contactpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactPage",
        ),
    ]
