# Generated by Django 5.2.2 on 2025-06-27 08:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0032_contactpage"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="background_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="thank_you_text",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Text to display after form sent successfully"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="intro",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Introduction text above the form"
            ),
        ),
    ]
