# Generated by Django 5.2.2 on 2025-06-27 08:51

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0033_contactpage_background_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactpage",
            name="intro",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="thank_you_text",
        ),
        migrations.AddField(
            model_name="contactpage",
            name="business_hours",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="checkbox_choices",
            field=models.TextField(
                default="1,2,3", help_text="Enter comma-separated checkbox options"
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="gallery_images",
            field=wagtail.fields.StreamField(
                [("image", 0)],
                blank=True,
                block_lookup={0: ("wagtail.images.blocks.ImageChooserBlock", (), {})},
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="heading",
            field=models.CharField(default="Contact Us Advanced", max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="intro_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="map_api_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="map_lat",
            field=models.FloatField(default=37.09024),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="map_lng",
            field=models.FloatField(default=-95.71289),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="map_zoom",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="office_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="office_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="office_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="radio_choices",
            field=models.TextField(
                default="1,2,3", help_text="Enter comma-separated radio options"
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="subheading",
            field=models.CharField(default="Get in touch with us", max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="subject_choices",
            field=models.TextField(
                default="Option 1,Option 2,Option 3,Option 4",
                help_text="Enter comma-separated subject options",
            ),
        ),
    ]
