# Generated by Django 5.2.2 on 2025-07-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0034_remove_contactpage_intro_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactpage",
            name="business_hours",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="checkbox_choices",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="radio_choices",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="subject_choices",
        ),
    ]
