# Generated by Django 5.2.2 on 2025-07-01 07:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0035_remove_contactpage_business_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalfooter",
            name="footer",
            field=wagtail.fields.StreamField(
                [("footer", 7)],
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: ("wagtail.blocks.CharBlock", (), {}),
                    5: ("wagtail.blocks.URLBlock", (), {}),
                    6: ("wagtail.blocks.StructBlock", [[("label", 4), ("url", 5)]], {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("logo", 0),
                                ("description", 1),
                                ("view_more_link", 2),
                                ("address", 3),
                                ("phone", 3),
                                ("email", 3),
                                ("link_1", 6),
                                ("link_2", 6),
                                ("link_3", 6),
                                ("copyright", 4),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="footer",
            field=wagtail.fields.StreamField(
                [("footer", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: ("wagtail.blocks.CharBlock", (), {}),
                    5: ("wagtail.blocks.URLBlock", (), {}),
                    6: ("wagtail.blocks.StructBlock", [[("label", 4), ("url", 5)]], {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("logo", 0),
                                ("description", 1),
                                ("view_more_link", 2),
                                ("address", 3),
                                ("phone", 3),
                                ("email", 3),
                                ("link_1", 6),
                                ("link_2", 6),
                                ("link_3", 6),
                                ("copyright", 4),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="marketingpage",
            name="footer",
            field=wagtail.fields.StreamField(
                [("footer", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: ("wagtail.blocks.CharBlock", (), {}),
                    5: ("wagtail.blocks.URLBlock", (), {}),
                    6: ("wagtail.blocks.StructBlock", [[("label", 4), ("url", 5)]], {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("logo", 0),
                                ("description", 1),
                                ("view_more_link", 2),
                                ("address", 3),
                                ("phone", 3),
                                ("email", 3),
                                ("link_1", 6),
                                ("link_2", 6),
                                ("link_3", 6),
                                ("copyright", 4),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
