# Generated by Django 5.2.2 on 2025-07-01 07:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0036_alter_globalfooter_footer_alter_homepage_footer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero_carousel", 6),
                    ("fixed_solutions", 14),
                    ("logo_carousel", 21),
                    ("style_switcher", 27),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Select the image for this carousel slide.",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading text", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional subheading text", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text on the button", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL the button will link to", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("heading", 1),
                                ("subheading", 2),
                                ("button_text", 3),
                                ("button_link", 4),
                            ]
                        ],
                        {},
                    ),
                    6: ("wagtail.blocks.ListBlock", (5,), {}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main heading above the solutions section",
                            "required": True,
                        },
                    ),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional subheading text", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title for the solution item", "required": True},
                    ),
                    10: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Background image", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional link for the solution",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("image", 10), ("link", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {"help_text": "Add 5 items: 2 top, 3 bottom."},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 7), ("subheading", 8), ("solutions", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main title", "required": True},
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {}),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (16,),
                        {"help_text": "Words to rotate"},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle below the heading", "required": True},
                    ),
                    19: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    20: (
                        "wagtail.blocks.ListBlock",
                        (19,),
                        {"help_text": "Upload logos"},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 15),
                                ("rotating_words", 17),
                                ("subtitle", 18),
                                ("logos", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading", "required": True},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Highlighted word in heading", "required": True},
                    ),
                    24: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Main paragraph text", "required": True},
                    ),
                    25: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional extra paragraph", "required": False},
                    ),
                    26: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Associated image", "required": True},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 22),
                                ("highlight", 23),
                                ("description", 24),
                                ("extra_text", 25),
                                ("image", 26),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
